#cloud-config

users:
  - default
# On créé l'utilisateur avec droits sudo en précisant sa clé SSH publique
system_info:
   default_user:
     name: arch
     password: password
     lock_passwd: true
     gecos: arch Cloud User
     groups: [wheel, adm]
     sudo: ["ALL=(ALL) NOPASSWD:ALL"]
     shell: /bin/bash
