name: vagrant-up

on: [push]

jobs:
  vagrant-up:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Vagrant boxes
        uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: Show Vagrant version
        run: vagrant --version
        # Fix 3 for issue connection reset, retrying...
        #- name: Update Vagrant
        #  run: brew install hashicorp/tap/hashicorp-vagrant
        #  run: vagrant --version

      # Fix issue connection reset, retrying...
      - name: Run vagrant plugin repair 
        run: vagrant plugin repair

      - name: Run vagrant plugin update
        run: vagrant plugin update

      - name: Run vagrant up
        run: vagrant up #--debug

      - name: ssh into box after boot
        run: vagrant ssh -c "echo 'hello world!'"
